language: python
jobs:
  include:
    - name: "Python 3.8 on Linux"
      os: linux
      dist: xenial
      language: python
      python: 3.8
      before_install:
        - sudo pip3 install tox
        - echo "alias python=python3" >> ~/.bashrc

install: pip3 install --upgrade pip3
script:
  - tox -e short-test
