language: python
jobs:
  include:
    - name: "Python 3.8 on Linux"
      os: linux
      dist: xenial
      language: python
      python: 3.8
      before_install:
        - sudo apt update
        - sudo apt install python3-pip
        - python3.8 -m pip install tox
script:
  - tox -e short-test
