language: python
jobs:
  include:
    - name: "Python 3.8.0 on ARM64 Linux"
      python: 3.8
      os: linux
      arch: arm64
      before_install:
        - sudo pip install tox
        
install: pip install --upgrade pip
script:
  - tox -e short-test
