language: python
jobs:
  include:
    - name: "Python 3.8 on Linux"
      os: linux
      dist: xenial
      language: python
      python: 3.8
      before_install:
        - sudo apt-get update
        - sudo pip install tox
        - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10

install: pip install --upgrade pip
script:
  - tox -e short-test
