language: python
jobs:
  include:
    - name: "Python 3.8 on Linux"
      os: linux
      dist: xenial
      language: python
      python: 3.8
      before_install:
        - sudo apt-get update
        - sudo apt install python3-pip
        - sudo pip install tox
install: pip3 install --upgrade pip
script:
  - tox -e short-test
