language: python
jobs:
  include:
    - name: "Python 3.8.0 on ARM64 Linux"
      os: linux
      before_install:
        - sudo apt update
        - sudo apt install software-properties-common
        - sudo add-apt-repository ppa:deadsnakes/ppa -y
        - sudo apt install python3.8
        - sudo pip install tox

install: pip install --upgrade pip
script:
  - tox -e short-test
