language: python
jobs:
  include:
    - name: "Python 3.8.0 on Linux"
      os: linux
      python: 3.8
      name: Python 3.8 with required dependencies and measure coverage
      stage: Initial tests
      env: TOXENV=py38-test

install: pip install --upgrade pip
script:
  - tox -e short-test
