language: python
jobs:
  include:
    - name: "Python 3.8 on Linux"
      os: linux
      dist: xenial
      language: python
      python: 3.8
      before_install:
        - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        - python3.8 get-pip.py
        - sudo python3.8 -m pip install tox
        - echo "alias python=python3.8" >> ~/.bashrc

install: pip install --upgrade pip
script:
  - tox -e short-test
