language: python
jobs:
  include:
    - name: "Python version 3.7 on Linux"
      os: linux
      before_install:
        - sudo apt update
        - sudo apt install python3.7 python3-pip
        - sudo pip install tox

install: pip install --upgrade pip
script:
  - tox -e short-test
