language: python
jobs:
  include:
    - name: "Python 3.8.0 on Linux"
      python:
        - "3.8"
      os: linux
      dist: xenial
      before_install:
        - sudo pip install tox-travis
        - sudo pip install virtualenv

install: pip install --upgrade pip
script:
  - tox -e short-test
