language: python
jobs:
  include:
    - name: "Python 3.8.0 on ARM64 Linux"
      python: 3.8
      os: linux
      arch: arm64
      before_install:
        - sudo apt-get install build-essential checkinstall
        - sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
        - cd /opt
        - sudo wget https://www.python.org/ftp/python/3.8.7/Python-3.8.7.tgz
        - sudo tar xzf Python-3.8.7.tgz
        - cd Python-3.8.7
        - sudo ./configure --enable-optimizations
        - sudo make altinstall
        - sudo pip install tox

install: pip install --upgrade pip
script:
  - tox -e short-test
