language: python
jobs:
  include:
    - name: "Python version 2.7 on Linux"
      os: linux
      language: python
      python:
        - 3.8
      before_install:
        - python -m pip install -U pip
        - sudo pip install tox
script:
  - tox -e short-test
