language: python
jobs:
  include:
    - name: "Python 3.8 on Linux"
      os: linux
      dist: xenial
      language: python
      python: 3.8
      before_install:
        - sudo pip install tox
        - cat "alias python=python3" >>  ~/.bash_profile
install: pip install --upgrade pip
script:
  - tox -e short-test
