language: python
jobs:
  include:
    - name: "Python 3.8 on Linux, with optional dependencies and benchmark"
      os: linux
      dist: xenial
      language: python
      python: 3.7
      service:
        - xvfb
      install:
        # Native libraries for pycairo / pygobject
        - sudo apt-get update
        # Coverage will be reported for the Python 3.7 Linux build
        - pip3 install coveralls -y
        - pip3 uninstall requests
        - pipenv shell
        - pip install requests -y
        - pytest --version
        - pip3 install pytest -y

        - sudo pip install tox-travis

install: pip install --upgrade pip
script:
  - tox -e short-test
