language: python
jobs:
  include:
    -- name: "Python 3.8 on Linux"
      os: linux
      dist: xenial
      language: python
      python: 3.8

install: sudo apt install python3-pip
script:
  - tox -e short-test
