language: python

python:
- 3.8
- 3.7

matrix:
  include:
  - os: linux
    name: PEP8 MyPy Coverage
    python: 3.9
    install:
      - sudo apt update
      - sudo pip install tox
      - sudo pip3 uninstall pytest -y
      - pipenv shell
      - pip install pytest


install: pip install --upgrade pip

script: pytest
